### ISSUE TITLE
The purpose of this project in full details.

### ISSUE THREAD

**Issue by Isamonyeseala** [code-Crafter-Project/Code-Crafters#1]

**Comment by Isamonyeseala** [comment]
Should we have a whole section dedicated to this or just include it in the Business background?

**Comment by tshavhanigift** [comment]
Everything

**Comment by ThabisoSydney** [comment]
creating an Integrated Library System for their library. Our ILS will use four modules which are circulation, cataloging, security & privacy and OPAC. The system will enable patrons to use the self-service machine to check-in and check-out books. ILS will be handling the circulation of library items, returns, holds, renewals, and fines.
